server {
    listen 80;
    server_name _;

    location = / {
        return 302 /mky/;
    }

    location /mky/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /mky/index.html;
    }
}
